#thread pool config



ThreadPool.cpu.CorePoolSize=11
ThreadPool.cpu.MaximumPoolSize=11
ThreadPool.cpu.QueueCapacity=2048
#  s
ThreadPool.cpu.KeepAliveTime=60



ThreadPool.io.CorePoolSize=16
ThreadPool.io.MaximumPoolSize=32
ThreadPool.io.QueueCapacity=2048
#  s
ThreadPool.io.KeepAliveTime=60